# Generated by Django 3.0.3 on 2020-03-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('base', '0002_aboutpage_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
