# Generated by Django 3.0.3 on 2020-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200318_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured_intro',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
