# Generated by Django 3.0.3 on 2020-03-18 12:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blogpage_featured_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspage',
            name='body',
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project_name', models.CharField(max_length=250)),
                ('project_description', models.CharField(max_length=250)),
                ('project_url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.ProjectsPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
