# Generated by Django 3.0.3 on 2020-03-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('base', '0011_resumepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumePage',
        ),
    ]
